added --wildcard-queries argument

diff --git a/braxfr b/braxfr
--- a/braxfr
+++ b/braxfr
@@ -27,6 +27,7 @@ SKIP_TTL=0
 TCP=0
 VERBOSE=0
 WAIT=3
+WC_QUERIES=3
 WILDCARD_24=0
 
 
@@ -171,6 +172,9 @@ while test $# -gt 0; do
       echo "                                a wildcard test resulting in 192.168.1.233 will"
       echo "                                match any IP address in 192.168.1.0/24"
       echo "                                "
+      echo "  --wildcard-queries=WC_QUERIES The number of queries to perform when checking "
+      echo "                                for wildcard records - default is 3"
+      echo "                                "
       echo "  -x, --max-ns-cons=MAX_NS_CONS Max concurrent queries for each NAME_SERVER. For"
       echo "                                example, if MAX_NS_CONS=2, DICTIONARY contains"
       echo "                                4k words, NAME_SERVERS defined 1k servers, and"
@@ -291,6 +295,10 @@ while test $# -gt 0; do
     --wildcard-24)
       shift
       WILDCARD_24=1
+      ;;
+    --wildcard-queries*)
+      WC_QUERIES=`echo $1 | sed -e 's/^[^=]*=//g'`
+      shift
       ;;
     --ns-per-query*)
       NS_PER_QUERY=`echo $1 | sed -e 's/^[^=]*=//g'`
@@ -718,6 +726,13 @@ if [ -z $NO_WILDCARD_CHECK ]; then
   fi
 fi
 
+# WC_QUERIES
+wc_queries=$(($WC_QUERIES * 1))
+if [ $wc_queries -le 0 ]; then
+  >&2 echo "--wildcard-queries=$WC_QUERIES is invalid"
+  exit 1
+fi
+
 # NS_PER_QUERY
 ns_per_query=$(($NS_PER_QUERY * 1))
 if [ $ns_per_query -le 0 ]; then
@@ -776,7 +791,6 @@ rr_types=()
 rr_br_types=()
 has_a=0
 has_aaaa=0
-has_cname=0
 for type in ${RR_TYPES//,/ }; do
   type_lower=$(echo "$type" | awk '{print tolower($0)}')
   if [ ${type_lower::3} = "br_" ]; then
@@ -785,8 +799,6 @@ for type in ${RR_TYPES//,/ }; do
       has_a=1
     elif [ ${type_lower:3} = "aaaa" ]; then
       has_aaaa=1
-    elif [ ${type_lower:3} = "cname" ]; then
-      has_cname=1
     fi
   else
     rr_types+=($type)
@@ -1009,35 +1021,33 @@ for DOMAIN in ${DOMAINS[@]}; do
         ip=
         qtype=$type
         if [ $type = "AAAA" ] && [ $has_aaaa -eq 1 ]; then
-          ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} AAAA" 1)
-          ns_ptr=$(increment_ns_ptr)
-          if [ "$ip" = "" ]; then
-            ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} AAAA" 1)
-          fi
-          ns_ptr=$(increment_ns_ptr)
-          if [ "$ip" = "" ]; then
-            ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} AAAA" 1)
-          fi
-        elif [ $type = "A" ] && [ $has_a -eq 1 ]; then 
-          ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} A" 1)
-          ns_ptr=$(increment_ns_ptr)
-          if [ "$ip" = "" ]; then
-            ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} A" 1)
-          fi
-          ns_ptr=$(increment_ns_ptr)
-          if [ "$ip" = "" ]; then
-            ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} A" 1)
-          fi
-        elif [ $type = "CNAME" ] && [ $has_cname -eq 1 ]; then 
-          ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} CNAME" 1)
-          ns_ptr=$(increment_ns_ptr)
-          if [ "$ip" = "" ]; then
-            ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} CNAME" 1)
-          fi
-          ns_ptr=$(increment_ns_ptr)
-          if [ "$ip" = "" ]; then
-            ip=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} CNAME" 1)
-          fi
+          ip=
+          for ((i = 0; i < $WC_QUERIES; ++i)); do
+            temp=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} AAAA" 1)
+            ns_ptr=$(increment_ns_ptr)
+            if [ "$temp" != "" ]; then
+              ip="$ip $temp"
+            fi
+          done
+        elif [ $type = "A" ] && [ $has_a -eq 1 ]; then
+          ip=
+          for ((i = 0; i < $WC_QUERIES; ++i)); do
+            temp=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} A" 1)
+            ns_ptr=$(increment_ns_ptr)
+            if [ "$temp" != "" ]; then
+              ip="$ip $temp"
+            fi
+          done
+        elif [ $type = "CNAME" ] && [ $has_a -eq 1 ]; then
+          ip=
+          for ((i = 0; i < $WC_QUERIES; ++i)); do
+            temp=$(dig_cmd "braxfr${RANDOM}.${DOMAIN} CNAME" 1)
+            ns_ptr=$(increment_ns_ptr)
+            if [ "$temp" != "" ]; then
+              ip=$temp
+              break
+            fi
+          done
         fi
         
         if [ "$ip" != "" ]; then
